"""
DOCX Documentation Generator (DEPRECATED - SLOW)

⚠️ WARNING: This script is DEPRECATED. Use md_to_docx.py instead!

WHY:
- This script regenerates DOCX with LLM calls (~30 minutes)
- md_to_docx.py converts existing Markdown to DOCX (<1 second)
- 99.9% faster with same quality output

RECOMMENDED WORKFLOW:
1. python -m scripts.run_pipeline  (generates Markdown once)
2. python -m scripts.md_to_docx     (converts to DOCX instantly)

Generates professional Word documents from SoapUI project data
"""

import json
import logging
from pathlib import Path
from typing import Dict, Any, List
from collections import defaultdict
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

# Add parent directory to path for imports
import sys
sys.path.append(str(Path(__file__).parent.parent))

from core.llm_client import LLMClient

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(name)s | %(message)s'
)
logger = logging.getLogger("DocxDocumentationGenerator")


class DocxDocumentationGenerator:
    """Generates DOCX documentation from enriched SoapUI data"""

    def __init__(self, enriched_data: Dict[str, Any], llm_client: LLMClient):
        self.data = enriched_data
        self.llm = llm_client
        self.doc = Document()
        self._setup_styles()

    def _setup_styles(self):
        """Setup custom styles for the document"""
        styles = self.doc.styles

        # Title style
        if 'CustomTitle' not in styles:
            title_style = styles.add_style('CustomTitle', WD_STYLE_TYPE.PARAGRAPH)
            title_style.font.size = Pt(24)
            title_style.font.bold = True
            title_style.font.color.rgb = RGBColor(0, 51, 102)

        # Section heading style
        if 'SectionHeading' not in styles:
            section_style = styles.add_style('SectionHeading', WD_STYLE_TYPE.PARAGRAPH)
            section_style.font.size = Pt(16)
            section_style.font.bold = True
            section_style.font.color.rgb = RGBColor(0, 112, 192)

        # Subsection heading style
        if 'SubsectionHeading' not in styles:
            subsection_style = styles.add_style('SubsectionHeading', WD_STYLE_TYPE.PARAGRAPH)
            subsection_style.font.size = Pt(14)
            subsection_style.font.bold = True
            subsection_style.font.color.rgb = RGBColor(68, 84, 106)

    def generate(self) -> Document:
        """Generate complete DOCX documentation"""
        logger.info("=" * 60)
        logger.info("DOCX DOCUMENTATION GENERATION")
        logger.info("=" * 60)

        # Cover Page
        self._add_title()

        # Table of Contents
        self._add_table_of_contents()

        # Executive Summary
        self._add_executive_summary()

        # Section 1: Project Details Overview
        self._add_project_overview()

        # Section 2: Active/Inactive Test Cases Count
        self._add_test_case_counts()

        # Section 3: Test Case Insights (MAIN SECTION)
        self._add_test_case_insights()

        # Section 4: Unique Endpoints
        self._add_unique_endpoints()

        # Section 5: Queue Details
        self._add_queue_details()

        # Section 6: Operations Covered
        self._add_operations_covered()

        # Section 7-12: Manual Entry Sections
        self._add_manual_sections()

        # Add footer with page numbers
        self._add_footer()

        logger.info("=" * 60)
        logger.info("DOCX GENERATION COMPLETE")
        logger.info("=" * 60)

        return self.doc

    def _add_title(self):
        """Add professional cover page with title and project name"""
        project = self.data.get("project", {})
        project_name = project.get("name", "Unknown Project")

        # Add vertical spacing
        for _ in range(5):
            self.doc.add_paragraph()

        # Main Title: "Understanding Document"
        title = self.doc.add_heading("Understanding Document", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title.runs[0]
        title_run.font.size = Pt(32)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(0, 51, 102)

        # Add spacing
        self.doc.add_paragraph()

        # Project Name
        project_para = self.doc.add_paragraph()
        project_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        project_run = project_para.add_run(f"Project: {project_name}")
        project_run.font.size = Pt(18)
        project_run.font.color.rgb = RGBColor(68, 84, 106)

        # Add spacing
        for _ in range(2):
            self.doc.add_paragraph()

        # Generated by line
        generated_para = self.doc.add_paragraph()
        generated_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        generated_run = generated_para.add_run("AI-Powered SoapUI Documentation")
        generated_run.font.size = Pt(12)
        generated_run.font.italic = True
        generated_run.font.color.rgb = RGBColor(128, 128, 128)

        # Date
        from datetime import datetime
        date_para = self.doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_run = date_para.add_run(datetime.now().strftime("%B %d, %Y"))
        date_run.font.size = Pt(11)
        date_run.font.color.rgb = RGBColor(128, 128, 128)

        # Page break after cover
        self.doc.add_page_break()

    def _add_table_of_contents(self):
        """Add table of contents page"""
        # Title
        toc_heading = self.doc.add_heading("Table of Contents", level=1)
        toc_heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

        self.doc.add_paragraph()

        # TOC entries
        toc_items = [
            "Executive Summary",
            "Section 1: Project Details Overview",
            "Section 2: Active/Inactive Test Cases Count",
            "Section 3: Test Case Insights",
            "Section 4: Unique Endpoints",
            "Section 5: Queue Details (Destinations)",
            "Section 6: Operations Covered",
            "Section 7: Observations Found",
            "Section 8: Defects Raised",
            "Section 9: Tester",
            "Section 10: Date of Execution/Completion",
            "Section 11: Bundle Flow Description",
            "Section 12: Attachments"
        ]

        for idx, item in enumerate(toc_items, 1):
            p = self.doc.add_paragraph()
            p.add_run(f"{idx}. {item}")
            p.paragraph_format.left_indent = Inches(0.5)

        self.doc.add_page_break()

    def _add_executive_summary(self):
        """Add executive summary section"""
        self.doc.add_heading("Executive Summary", level=1)

        test_suites = self.data.get("test_suites", [])
        project = self.data.get("project", {})

        # Calculate statistics
        total_suites = len(test_suites)
        total_cases = sum(len(suite.get("test_cases", [])) for suite in test_suites)
        enabled_cases = sum(
            1 for suite in test_suites
            for tc in suite.get("test_cases", [])
            if tc.get("enabled", True)
        )
        disabled_cases = total_cases - enabled_cases

        # Summary paragraph
        summary_text = (
            f"This document provides comprehensive test documentation for the "
            f"{project.get('name', 'SoapUI')} project. The project contains "
            f"{total_suites} test suite(s) with a total of {total_cases} test case(s), "
            f"of which {enabled_cases} are active and {disabled_cases} are inactive. "
            f"Each test case has been analyzed using AI to provide detailed insights "
            f"into test objectives, validations, and potential issues."
        )

        p = self.doc.add_paragraph(summary_text)
        p.paragraph_format.line_spacing = 1.5

        self.doc.add_paragraph()

        # Key statistics table
        self.doc.add_heading("Key Statistics", level=2)

        stats_table = self.doc.add_table(rows=4, cols=2)
        stats_table.style = 'Light Grid Accent 1'

        stats_table.rows[0].cells[0].text = "Metric"
        stats_table.rows[0].cells[1].text = "Value"

        stats_table.rows[1].cells[0].text = "Total Test Suites"
        stats_table.rows[1].cells[1].text = str(total_suites)

        stats_table.rows[2].cells[0].text = "Total Test Cases"
        stats_table.rows[2].cells[1].text = str(total_cases)

        stats_table.rows[3].cells[0].text = "Active Test Cases"
        stats_table.rows[3].cells[1].text = str(enabled_cases)

        # Make header bold
        for cell in stats_table.rows[0].cells:
            cell.paragraphs[0].runs[0].font.bold = True

        self.doc.add_page_break()

    def _add_project_overview(self):
        """Section 1: Project Details Overview"""
        self.doc.add_heading("Section 1: Project Details Overview", level=1)

        test_suites = self.data.get("test_suites", [])

        for suite in test_suites:
            suite_name = suite.get("name", "Unnamed Suite")

            # Get only enabled test cases
            enabled_cases = [
                tc for tc in suite.get("test_cases", [])
                if tc.get("enabled", True)
            ]

            if enabled_cases:
                # Add test suite name
                p = self.doc.add_paragraph()
                p.add_run(suite_name).bold = True

                # Add enabled test cases as bullets
                for tc in enabled_cases:
                    tc_name = tc.get("name", "Unnamed Test Case")
                    self.doc.add_paragraph(tc_name, style='List Bullet')

        self.doc.add_page_break()

    def _add_test_case_counts(self):
        """Section 2: Active/Inactive Test Cases Count"""
        self.doc.add_heading("Section 2: Active/Inactive Test Cases Count", level=1)

        test_suites = self.data.get("test_suites", [])

        enabled_count = 0
        disabled_count = 0

        for suite in test_suites:
            for tc in suite.get("test_cases", []):
                if tc.get("enabled", True):
                    enabled_count += 1
                else:
                    disabled_count += 1

        total_count = enabled_count + disabled_count

        # Add as a simple table
        table = self.doc.add_table(rows=4, cols=2)
        table.style = 'Light Grid Accent 1'

        table.rows[0].cells[0].text = "Metric"
        table.rows[0].cells[1].text = "Count"

        table.rows[1].cells[0].text = "Enabled Test Cases"
        table.rows[1].cells[1].text = str(enabled_count)

        table.rows[2].cells[0].text = "Disabled Test Cases"
        table.rows[2].cells[1].text = str(disabled_count)

        table.rows[3].cells[0].text = "Total Test Cases"
        table.rows[3].cells[1].text = str(total_count)

        # Make header row bold
        for cell in table.rows[0].cells:
            cell.paragraphs[0].runs[0].font.bold = True

        self.doc.add_page_break()

    def _add_test_case_insights(self):
        """Section 3: Test Case Insights (MAIN SECTION)"""
        self.doc.add_heading("Section 3: Test Case Insights", level=1)

        p = self.doc.add_paragraph()
        p.add_run("This section provides AI-generated analysis of each enabled test case, "
                  "including test objectives, validations, and potential issues.").italic = True
        p.paragraph_format.line_spacing = 1.5
        self.doc.add_paragraph()

        test_suites = self.data.get("test_suites", [])

        test_case_number = 1

        for suite in test_suites:
            suite_name = suite.get("name", "Unnamed Suite")

            # Get only enabled test cases
            enabled_cases = [
                tc for tc in suite.get("test_cases", [])
                if tc.get("enabled", True)
            ]

            if not enabled_cases:
                continue

            logger.info(f"Processing Test Suite: {suite_name}")

            # Add test suite heading
            suite_heading = self.doc.add_heading(f"Test Suite: {suite_name}", level=2)
            suite_heading.runs[0].font.color.rgb = RGBColor(0, 112, 192)

            for tc in enabled_cases:
                tc_name = tc.get("name", "Unnamed Test Case")
                logger.info(f"  Analyzing: {tc_name}")

                # Add test case number and name
                tc_heading = self.doc.add_heading(f"3.{test_case_number} {tc_name}", level=3)
                tc_heading.runs[0].font.color.rgb = RGBColor(68, 84, 106)

                # Add test metadata table
                meta_table = self.doc.add_table(rows=2, cols=2)
                meta_table.style = 'Light Grid Accent 1'

                meta_table.rows[0].cells[0].text = "Test Suite"
                meta_table.rows[0].cells[1].text = suite_name
                meta_table.rows[1].cells[0].text = "Test Case"
                meta_table.rows[1].cells[1].text = tc_name

                self.doc.add_paragraph()

                # Get AI summary
                summary = self._get_test_case_summary(tc, suite_name)

                # Add summary with better formatting
                summary_heading = self.doc.add_paragraph()
                summary_heading.add_run("Test Analysis:").bold = True

                summary_para = self.doc.add_paragraph(summary)
                summary_para.paragraph_format.line_spacing = 1.5
                summary_para.paragraph_format.left_indent = Inches(0.25)

                # Add test steps summary
                steps = tc.get("test_steps", [])
                if steps:
                    steps_heading = self.doc.add_paragraph()
                    steps_heading.add_run("Test Steps:").bold = True

                    for idx, step in enumerate(steps[:5], 1):  # Limit to 5 steps
                        step_name = step.get("name", "Unnamed Step")
                        step_type = step.get("type", "unknown")
                        self.doc.add_paragraph(
                            f"{idx}. {step_name} ({step_type})",
                            style='List Bullet'
                        )

                    if len(steps) > 5:
                        more_para = self.doc.add_paragraph(f"... and {len(steps) - 5} more steps")
                        more_para.runs[0].font.italic = True
                        more_para.runs[0].font.color.rgb = RGBColor(128, 128, 128)

                self.doc.add_paragraph()

                # Add separator line
                separator_para = self.doc.add_paragraph("_" * 80)
                separator_para.runs[0].font.color.rgb = RGBColor(200, 200, 200)
                self.doc.add_paragraph()

                test_case_number += 1

        self.doc.add_page_break()

    def _get_test_case_summary(self, test_case: Dict[str, Any], suite_name: str) -> str:
        """Get AI-generated summary for a test case"""
        tc_name = test_case.get("name", "Unnamed Test Case")
        steps = test_case.get("test_steps", [])

        # Build prompt for LLM
        steps_text = ""
        for idx, step in enumerate(steps, 1):
            step_name = step.get("name", "Unnamed Step")
            step_type = step.get("type", "unknown")
            steps_text += f"Step {idx}: {step_name} ({step_type})\n"

        # Get assertions summary
        assertions_text = ""
        for step in steps:
            for assertion in step.get("assertions", []):
                assertion_type = assertion.get("type", "unknown")
                assertion_name = assertion.get("name", "")
                assertions_text += f"- {assertion_type}: {assertion_name}\n"

        prompt = f"""Provide a concise 2-3 sentence summary of what this test case validates.

Test Suite: {suite_name}
Test Case: {tc_name}

Test Steps:
{steps_text}

Assertions:
{assertions_text}

Write a brief summary explaining the purpose and what this test validates. Keep it professional and clear."""

        try:
            system_prompt = "You are a QA documentation expert. Summarize test cases clearly and concisely in 2-3 sentences."
            summary = self.llm.chat([
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ])
            return summary.strip()
        except Exception as e:
            logger.error(f"Error generating summary for {tc_name}: {e}")
            return f"Test case validates the functionality of {tc_name} in the {suite_name} test suite."

    def _add_unique_endpoints(self):
        """Section 4: Unique Endpoints"""
        self.doc.add_heading("Section 4: Unique Endpoints", level=1)

        endpoints = set()

        test_suites = self.data.get("test_suites", [])
        for suite in test_suites:
            for tc in suite.get("test_cases", []):
                if not tc.get("enabled", True):
                    continue

                for step in tc.get("test_steps", []):
                    endpoint = step.get("endpoint")
                    if endpoint:
                        endpoints.add(endpoint)

        if endpoints:
            for idx, endpoint in enumerate(sorted(endpoints), 1):
                self.doc.add_paragraph(f"{idx}. {endpoint}", style='List Number')
        else:
            self.doc.add_paragraph("No endpoints found.", style='Body Text')

        self.doc.add_page_break()

    def _add_queue_details(self):
        """Section 5: Queue Details (Destinations)"""
        self.doc.add_heading("Section 5: Queue Details (Destinations)", level=1)

        p = self.doc.add_paragraph()
        p.add_run("Extracted from 'Destination' parameters in Properties/Parameter steps").italic = True
        self.doc.add_paragraph()

        destinations = set()

        test_suites = self.data.get("test_suites", [])
        for suite in test_suites:
            for tc in suite.get("test_cases", []):
                if not tc.get("enabled", True):
                    continue

                for step in tc.get("test_steps", []):
                    step_type = step.get("type", "")

                    # Look for properties or parameter steps
                    if step_type in ["properties", "transfer", "groovy"]:
                        # Check for Destination in properties
                        properties = step.get("properties", {})
                        if "Destination" in properties:
                            dest_value = properties["Destination"]
                            if dest_value:
                                destinations.add(dest_value)

                        # Check in config
                        config = step.get("config", {})
                        if isinstance(config, dict) and "Destination" in config:
                            dest_value = config["Destination"]
                            if dest_value:
                                destinations.add(dest_value)

        if destinations:
            for idx, dest in enumerate(sorted(destinations), 1):
                self.doc.add_paragraph(f"{idx}. {dest}", style='List Number')
        else:
            self.doc.add_paragraph("No queue destinations found.", style='Body Text')

        self.doc.add_page_break()

    def _add_operations_covered(self):
        """Section 6: Operations Covered"""
        self.doc.add_heading("Section 6: Operations Covered", level=1)

        rest_methods = set()
        soap_operations = set()

        test_suites = self.data.get("test_suites", [])
        for suite in test_suites:
            for tc in suite.get("test_cases", []):
                if not tc.get("enabled", True):
                    continue

                for step in tc.get("test_steps", []):
                    step_type = step.get("type", "")

                    # REST methods
                    if step_type in ["restrequest", "httprequest"]:
                        method = step.get("method")
                        if method:
                            rest_methods.add(method.upper())

                    # SOAP operations
                    if step_type in ["request", "soaprequest"]:
                        operation = step.get("operation")
                        if operation:
                            soap_operations.add(operation)

        # Add REST methods
        if rest_methods:
            self.doc.add_heading("REST Methods:", level=2)
            for method in sorted(rest_methods):
                self.doc.add_paragraph(method, style='List Bullet')

        # Add SOAP operations
        if soap_operations:
            self.doc.add_heading("SOAP Operations:", level=2)
            for operation in sorted(soap_operations):
                self.doc.add_paragraph(operation, style='List Bullet')

        if not rest_methods and not soap_operations:
            self.doc.add_paragraph("No operations found.", style='Body Text')

        self.doc.add_page_break()

    def _add_manual_sections(self):
        """Add manual entry sections (7-12)"""
        manual_sections = [
            "Section 7: Observations Found",
            "Section 8: Defects Raised",
            "Section 9: Tester",
            "Section 10: Date of Execution/Completion",
            "Section 11: Bundle Flow Description",
            "Section 12: Attachments"
        ]

        for section_title in manual_sections:
            self.doc.add_heading(section_title, level=1)

            # Add placeholder text
            p = self.doc.add_paragraph()
            run = p.add_run("[To be filled by tester]")
            run.italic = True
            run.font.color.rgb = RGBColor(128, 128, 128)

            # Add some empty lines for manual entry
            self.doc.add_paragraph()
            self.doc.add_paragraph()
            self.doc.add_paragraph()

            self.doc.add_page_break()

    def _add_footer(self):
        """Add footer with page numbers and project info"""
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement

        section = self.doc.sections[0]
        footer = section.footer

        # Create footer paragraph
        footer_para = footer.paragraphs[0]
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add project name on left
        project_name = self.data.get("project", {}).get("name", "SoapUI Project")
        run_left = footer_para.add_run(f"{project_name}    ")
        run_left.font.size = Pt(9)
        run_left.font.color.rgb = RGBColor(128, 128, 128)

        # Add separator
        footer_para.add_run("|    ")

        # Add page number
        run_page = footer_para.add_run("Page ")
        run_page.font.size = Pt(9)
        run_page.font.color.rgb = RGBColor(128, 128, 128)

        # Add page number field
        fldChar1 = OxmlElement('w:fldChar')
        fldChar1.set(qn('w:fldCharType'), 'begin')

        instrText = OxmlElement('w:instrText')
        instrText.set(qn('xml:space'), 'preserve')
        instrText.text = "PAGE"

        fldChar2 = OxmlElement('w:fldChar')
        fldChar2.set(qn('w:fldCharType'), 'end')

        run_page._r.append(fldChar1)
        run_page._r.append(instrText)
        run_page._r.append(fldChar2)

    def save(self, output_path: Path):
        """Save document to file"""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        self.doc.save(str(output_path))
        logger.info(f"Document saved to: {output_path}")


def main():
    """Main execution"""
    try:
        # Load enriched data
        enriched_path = Path("output/layer2_enriched.json")
        logger.info(f"Loading enriched data from: {enriched_path}")

        with open(enriched_path, "r", encoding="utf-8") as f:
            enriched_data = json.load(f)

        # Initialize LLM client
        logger.info("Initializing LLM client from .env configuration")
        llm_client = LLMClient()

        # Generate documentation
        generator = DocxDocumentationGenerator(enriched_data, llm_client)
        doc = generator.generate()

        # Save document
        output_path = Path("output/soapui_documentation.docx")
        generator.save(output_path)

        logger.info(f"✓ Documentation generated successfully: {output_path}")

    except Exception as e:
        logger.error(f"Error generating documentation: {e}", exc_info=True)
        raise


if __name__ == "__main__":
    main()
