"""
Convert Markdown documentation to professional DOCX format
This is much faster than regenerating with LLM (seconds vs 30+ minutes)
"""

import re
from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s'
)
logger = logging.getLogger("MarkdownToDocx")


class MarkdownToDocxConverter:
    """Convert Markdown to professional DOCX"""

    # Professional color palette
    COLOR_PRIMARY = RGBColor(0, 102, 204)      # Deep Blue (titles)
    COLOR_HEADING = RGBColor(0, 120, 215)      # Bright Blue (H1)
    COLOR_SUBHEADING = RGBColor(0, 153, 153)   # Teal (H2, H3)
    COLOR_ACCENT = RGBColor(79, 129, 189)      # Medium Blue (accents)
    COLOR_TEXT_GRAY = RGBColor(102, 102, 102)  # Professional Gray
    COLOR_LIGHT_GRAY = RGBColor(150, 150, 150) # Light Gray (footers)

    def __init__(self, markdown_path: str):
        self.markdown_path = Path(markdown_path)
        self.doc = Document()
        self.project_name = "SoapUI Project"
        self._set_narrow_margins()

    def _set_narrow_margins(self):
        """Set narrow margins (0.5 inches all around)"""
        for section in self.doc.sections:
            section.top_margin = Inches(0.5)
            section.bottom_margin = Inches(0.5)
            section.left_margin = Inches(0.5)
            section.right_margin = Inches(0.5)

    def convert(self, output_path: str):
        """Convert markdown to DOCX with professional formatting"""
        logger.info("Reading Markdown file...")

        with open(self.markdown_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Extract project name from markdown
        project_match = re.search(r'\*\*Project Name:\*\* (.+)', content)
        if project_match:
            self.project_name = project_match.group(1).strip()

        logger.info("Creating professional DOCX...")

        # Add cover page
        self._add_cover_page()

        # Add table of contents
        self._add_table_of_contents()

        # Add executive summary
        self._add_executive_summary(content)

        # Add project overview with proper table
        self._add_project_overview_section(content)

        # Convert remaining markdown content (API Inventory onwards)
        self._convert_markdown_content(content)

        # Add footer
        self._add_footer()

        # Save
        logger.info(f"Saving to: {output_path}")
        self.doc.save(output_path)
        logger.info("✓ Conversion complete!")

    def _add_cover_page(self):
        """Add professional cover page with narrow margins"""
        # Add vertical spacing
        for _ in range(4):
            self.doc.add_paragraph()

        # Main Title: "Understanding Document"
        title = self.doc.add_heading("Understanding Document", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title.runs[0]
        title_run.font.size = Pt(36)
        title_run.font.bold = True
        title_run.font.color.rgb = self.COLOR_PRIMARY

        # Add spacing
        self.doc.add_paragraph()

        # Project Name
        project_para = self.doc.add_paragraph()
        project_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        project_run = project_para.add_run(f"Project: {self.project_name}")
        project_run.font.size = Pt(20)
        project_run.font.bold = True
        project_run.font.color.rgb = self.COLOR_ACCENT

        # Add spacing
        for _ in range(2):
            self.doc.add_paragraph()

        # Generated by line
        generated_para = self.doc.add_paragraph()
        generated_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        generated_run = generated_para.add_run("AI-Powered SoapUI Documentation")
        generated_run.font.size = Pt(13)
        generated_run.font.italic = True
        generated_run.font.color.rgb = self.COLOR_TEXT_GRAY

        # Date
        date_para = self.doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_run = date_para.add_run(datetime.now().strftime("%B %d, %Y"))
        date_run.font.size = Pt(12)
        date_run.font.color.rgb = self.COLOR_LIGHT_GRAY

        self.doc.add_page_break()

    def _add_table_of_contents(self):
        """Add comprehensive table of contents with all test suites"""
        toc_heading = self.doc.add_heading("Table of Contents", level=1)
        toc_heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
        toc_heading.runs[0].font.color.rgb = self.COLOR_HEADING
        toc_heading.runs[0].font.size = Pt(18)

        self.doc.add_paragraph()

        # Main sections
        main_sections = [
            ("1", "Executive Summary", None),
            ("2", "Project Overview", None),
            ("3", "API Inventory", [
                "3.1 Summary",
                "3.2 Endpoints",
                "3.3 SOAP Operations"
            ]),
            ("4", "Test Suite Details", [
                "4.1 User Authentication Tests",
                "4.2 Product Management Tests",
                "4.3 Order Management Tests (SOAP)",
                "4.4 Payment Processing Tests",
                "4.5 End-to-End Integration Tests"
            ])
        ]

        for number, title, subsections in main_sections:
            # Main section
            p = self.doc.add_paragraph()
            run = p.add_run(f"{number}. {title}")
            run.bold = True
            run.font.size = Pt(12)
            run.font.color.rgb = self.COLOR_HEADING
            p.paragraph_format.left_indent = Inches(0.3)
            p.paragraph_format.space_after = Pt(6)

            # Subsections
            if subsections:
                for sub in subsections:
                    p_sub = self.doc.add_paragraph()
                    run_sub = p_sub.add_run(f"   {sub}")
                    run_sub.font.size = Pt(11)
                    run_sub.font.color.rgb = self.COLOR_TEXT_GRAY
                    p_sub.paragraph_format.left_indent = Inches(0.6)
                    p_sub.paragraph_format.space_after = Pt(3)

        self.doc.add_page_break()

    def _add_executive_summary(self, content: str):
        """Add executive summary"""
        heading = self.doc.add_heading("Executive Summary", level=1)
        heading.runs[0].font.color.rgb = self.COLOR_HEADING
        heading.runs[0].font.size = Pt(18)

        # Extract statistics from markdown
        total_cases = 0
        enabled_cases = 0
        disabled_cases = 0
        total_suites = 0

        suites_match = re.search(r'\*\*Test Suites:\*\* (\d+)', content)
        cases_match = re.search(r'\*\*Total Test Cases:\*\* (\d+)', content)
        enabled_match = re.search(r'\*\*Enabled Test Cases:\*\* (\d+)', content)
        disabled_match = re.search(r'\*\*Disabled Test Cases:\*\* (\d+)', content)

        if suites_match:
            total_suites = int(suites_match.group(1))
        if cases_match:
            total_cases = int(cases_match.group(1))
        if enabled_match:
            enabled_cases = int(enabled_match.group(1))
        if disabled_match:
            disabled_cases = int(disabled_match.group(1))

        # Summary paragraph
        summary_text = (
            f"This document provides comprehensive test documentation for the "
            f"{self.project_name} project. The project contains "
            f"{total_suites} test suite(s) with a total of {total_cases} test case(s), "
            f"of which {enabled_cases} are active and {disabled_cases} are inactive. "
            f"Each test case has been analyzed using AI to provide detailed insights "
            f"into test objectives, validations, and potential issues."
        )

        p = self.doc.add_paragraph(summary_text)
        p.paragraph_format.line_spacing = 1.5

        self.doc.add_paragraph()

        # Key statistics table
        stats_heading = self.doc.add_heading("Key Statistics", level=2)
        stats_heading.runs[0].font.color.rgb = self.COLOR_SUBHEADING
        stats_heading.runs[0].font.size = Pt(15)

        stats_table = self.doc.add_table(rows=4, cols=2)
        stats_table.style = 'Light Grid Accent 1'

        stats_table.rows[0].cells[0].text = "Metric"
        stats_table.rows[0].cells[1].text = "Value"

        stats_table.rows[1].cells[0].text = "Total Test Suites"
        stats_table.rows[1].cells[1].text = str(total_suites)

        stats_table.rows[2].cells[0].text = "Total Test Cases"
        stats_table.rows[2].cells[1].text = str(total_cases)

        stats_table.rows[3].cells[0].text = "Active Test Cases"
        stats_table.rows[3].cells[1].text = str(enabled_cases)

        # Make header bold
        for cell in stats_table.rows[0].cells:
            cell.paragraphs[0].runs[0].font.bold = True

        self.doc.add_page_break()

    def _add_project_overview_section(self, content: str):
        """Add properly formatted Project Overview section"""
        heading = self.doc.add_heading("Project Overview", level=1)
        heading.runs[0].font.color.rgb = self.COLOR_HEADING
        heading.runs[0].font.size = Pt(18)

        # Extract project name
        project_match = re.search(r'\*\*Project Name:\*\* (.+)', content)
        project_name = project_match.group(1).strip() if project_match else "Unknown Project"

        # Add project name as prominent text
        name_para = self.doc.add_paragraph()
        name_run = name_para.add_run(f"Project: {project_name}")
        name_run.font.size = Pt(16)
        name_run.font.bold = True
        name_run.font.color.rgb = self.COLOR_ACCENT
        name_para.paragraph_format.space_after = Pt(12)

        # Extract statistics
        test_suites = 0
        total_cases = 0
        enabled_cases = 0
        disabled_cases = 0

        suites_match = re.search(r'\*\*Test Suites:\*\* (\d+)', content)
        cases_match = re.search(r'\*\*Total Test Cases:\*\* (\d+)', content)
        enabled_match = re.search(r'\*\*Enabled Test Cases:\*\* (\d+)', content)
        disabled_match = re.search(r'\*\*Disabled Test Cases:\*\* (\d+)', content)

        if suites_match:
            test_suites = int(suites_match.group(1))
        if cases_match:
            total_cases = int(cases_match.group(1))
        if enabled_match:
            enabled_cases = int(enabled_match.group(1))
        if disabled_match:
            disabled_cases = int(disabled_match.group(1))

        # Create professional statistics table
        stats_table = self.doc.add_table(rows=5, cols=2)
        stats_table.style = 'Light Grid Accent 1'

        # Header row
        header_cells = stats_table.rows[0].cells
        header_cells[0].text = "Metric"
        header_cells[1].text = "Count"

        for cell in header_cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.color.rgb = self.COLOR_PRIMARY

        # Data rows
        data_rows = [
            ("Test Suites", str(test_suites)),
            ("Total Test Cases", str(total_cases)),
            ("Enabled Test Cases", str(enabled_cases)),
            ("Disabled Test Cases", str(disabled_cases))
        ]

        for idx, (label, value) in enumerate(data_rows, 1):
            row_cells = stats_table.rows[idx].cells
            row_cells[0].text = label
            row_cells[1].text = value

            # Style the value cells
            for paragraph in row_cells[1].paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.color.rgb = self.COLOR_ACCENT

        self.doc.add_page_break()

    def _convert_markdown_content(self, content: str):
        """Convert markdown content to DOCX"""
        lines = content.split('\n')

        in_code_block = False
        skip_until_api_inventory = True

        for line in lines:
            # Skip header until we reach API Inventory (Project Overview handled separately)
            if skip_until_api_inventory:
                if line.startswith('## API Inventory'):
                    skip_until_api_inventory = False
                    # Don't skip this line, process it
                continue

            # Handle code blocks
            if line.startswith('```'):
                in_code_block = not in_code_block
                continue

            if in_code_block:
                continue

            # Skip empty lines
            if not line.strip():
                continue

            # H1 headers (##)
            if line.startswith('## '):
                heading_text = line[3:].strip()
                heading = self.doc.add_heading(heading_text, level=1)
                heading.runs[0].font.color.rgb = self.COLOR_HEADING
                heading.runs[0].font.size = Pt(18)
                continue

            # H2 headers (###)
            if line.startswith('### '):
                heading_text = line[4:].strip()
                heading = self.doc.add_heading(heading_text, level=2)
                heading.runs[0].font.color.rgb = self.COLOR_SUBHEADING
                heading.runs[0].font.size = Pt(15)
                continue

            # H3 headers (####)
            if line.startswith('#### '):
                heading_text = line[5:].strip()
                heading = self.doc.add_heading(heading_text, level=3)
                heading.runs[0].font.color.rgb = self.COLOR_ACCENT
                heading.runs[0].font.size = Pt(13)
                continue

            # Horizontal rules
            if line.startswith('---'):
                separator_para = self.doc.add_paragraph("_" * 100)
                separator_para.runs[0].font.color.rgb = self.COLOR_SUBHEADING
                separator_para.runs[0].font.size = Pt(8)
                continue

            # Bullet points
            if line.startswith('- '):
                text = line[2:].strip()
                text = self._clean_markdown_formatting(text)
                self.doc.add_paragraph(text, style='List Bullet')
                continue

            # Numbered lists
            if re.match(r'^\d+\. ', line):
                text = re.sub(r'^\d+\. ', '', line).strip()
                text = self._clean_markdown_formatting(text)
                p = self.doc.add_paragraph(text)
                p.paragraph_format.left_indent = Inches(0.5)
                p.paragraph_format.line_spacing = 1.5
                continue

            # Regular paragraphs
            if line.strip():
                text = self._clean_markdown_formatting(line.strip())
                p = self.doc.add_paragraph(text)
                p.paragraph_format.line_spacing = 1.5

    def _clean_markdown_formatting(self, text: str) -> str:
        """Remove markdown formatting like **bold** and *italic*"""
        # Remove **bold**
        text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
        # Remove *italic*
        text = re.sub(r'\*(.+?)\*', r'\1', text)
        # Remove `code`
        text = re.sub(r'`(.+?)`', r'\1', text)
        return text

    def _add_footer(self):
        """Add footer with page numbers"""
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement

        section = self.doc.sections[0]
        footer = section.footer

        footer_para = footer.paragraphs[0]
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add project name
        run_left = footer_para.add_run(f"{self.project_name}    ")
        run_left.font.size = Pt(9)
        run_left.font.color.rgb = self.COLOR_LIGHT_GRAY

        # Add separator
        sep_run = footer_para.add_run("|    ")
        sep_run.font.color.rgb = self.COLOR_SUBHEADING

        # Add page number
        run_page = footer_para.add_run("Page ")
        run_page.font.size = Pt(9)
        run_page.font.color.rgb = self.COLOR_LIGHT_GRAY

        # Add page number field
        fldChar1 = OxmlElement('w:fldChar')
        fldChar1.set(qn('w:fldCharType'), 'begin')

        instrText = OxmlElement('w:instrText')
        instrText.set(qn('xml:space'), 'preserve')
        instrText.text = "PAGE"

        fldChar2 = OxmlElement('w:fldChar')
        fldChar2.set(qn('w:fldCharType'), 'end')

        run_page._r.append(fldChar1)
        run_page._r.append(instrText)
        run_page._r.append(fldChar2)


def main():
    """Convert markdown to DOCX"""
    markdown_path = "output/llm_documentation.md"
    output_path = "output/Understanding_Document.docx"

    logger.info("=" * 60)
    logger.info("MARKDOWN TO DOCX CONVERTER")
    logger.info("=" * 60)
    logger.info(f"Input: {markdown_path}")
    logger.info(f"Output: {output_path}")
    logger.info("")

    converter = MarkdownToDocxConverter(markdown_path)
    converter.convert(output_path)

    logger.info("=" * 60)
    logger.info("✅ CONVERSION COMPLETE!")
    logger.info("=" * 60)
    logger.info(f"Professional DOCX created: {output_path}")


if __name__ == "__main__":
    main()
